name: Build ilham 1

on:
  workflow_dispatch:
    inputs:
      jobId:
        description: 'Job ID from Bot'
        required: true
      userId:
        description: 'User ID'
        required: true
      payload:
        description: 'Build Payload (JSON)'
        required: true

jobs:
  build:
    uses: ilham-starts/ilham-1/.github/workflows/ilham.yml@main
    with:
      jobId: ${{ inputs.jobId }}
      userId: ${{ inputs.userId }}
      payload: ${{ inputs.payload }}